podTemplate(yaml: readTrusted('podTemplate.yaml'), containers: [
  containerTemplate(name: 'maven', image: 'maven:3.9.8-amazoncorretto-17', command: 'sleep', args: '99d')
  ], volumes: [
  persistentVolumeClaim(mountPath: '/root/.m2/repository', claimName: 'maven-repo-pvc', readOnly: false)
  ]) {

  node(POD_LABEL) {
    stage('Build a Maven project') {
      git credentialsId: 'jenkins', url: 'git@gitea.localhost.com:cicd/java-microservice.git'
      container('maven') {
        sh 'mvn clean install'
      }
    }
  }
}