repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: jenkins
  url: https://charts.jenkins.io  

releases:
- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: 4.10.1
  values:
  - ./manifests/charts/ingress-controller/values.yaml
- name: jenkins
  namespace: jenkins
  chart: jenkins/jenkins
  version: 5.4.2
  values:
  - ./manifests/charts/jenkins/values.yaml  