apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-microservice-2
  name: java-microservice-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-microservice-2
  strategy: {}
  template:
    metadata:
      labels:
        app: java-microservice-2
    spec:
      containers:
      - image: foo
        name: foo